name: Deploy lambda

on:
  push:
    branches:
      - main

jobs:
  deploy_lambda:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies and bundle code
        env:
          CI: true
        run: |
          npm ci
          npm run build -w backend
          cd backend/dist
          zip -r ../../publish.zip . # Zipea solo el contenido de la carpeta dist/src
          cd ../..

      - name: Deploy to AWS Lambda
        run: |
          aws lambda update-function-code --function-name chess-api --zip-file fileb://publish.zip --region us-east-2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
